Maquillaje/Maquillaje.WebUI/Models/EstadosCivilesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Maquillaje.WebUI.Models
{
    public class EstadosCivilesViewModel
    {
        [Display(Name = "ID")]
        public int est_ID { get; set; }

        [Display(Name = "Descripcion")]
        public string est_Descripcion { get; set; }

        //AUDITORIA

        [Display(Name = "Usuario Creación")]
        public string est_UsuarioCrea { get; set; }

        [Display(Name = "Fecha Creacion")]
        public DateTime? est_FechaCrea { get; set; }

        [Display(Name = "Usuario Modificación")]
        public string est_UsuarioModi { get; set; }

        [Display(Name = "Fecha Modificación")]
        public DateTime? est_FechaModi { get; set; }
    }
}

Maquillaje/Maquillaje.WebUI/Controllers/EstadosCivilesController.cs
using AutoMapper;
using Maquillaje.BusinessLogic.Services;
using Maquillaje.Entities.Entities;
using Maquillaje.WebUI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Maquillaje.WebUI.Controllers
{
    public class EstadosCivilesController : Controller
    {
        private readonly GeneralesService _generalesService;
        private readonly IMapper _mapper;


        public EstadosCivilesController(GeneralesService generalesService, IMapper mapper)
        {
            _generalesService = generalesService;
            _mapper = mapper;
        }

        [HttpGet("/EstadosCiviles/Listado")]
        public IActionResult Index()
        {
            try
            {
                if (HttpContext.Session.GetString("usu_Nombre") != null)
                {
                    ViewBag.usu_Nombre = HttpContext.Session.GetString("usu_Nombre");
                    ViewBag.suc_Descripcion = HttpContext.Session.GetString("suc_Descripcion");
                    ViewBag.usu_Id = HttpContext.Session.GetString("usu_ID");
                    ViewBag.suc_Id = HttpContext.Session.GetString("suc_Id");


            var listado = _generalesService.ListadoEstadosCiviles();
            var listadoMapeado = _mapper.Map<IEnumerable<EstadosCivilesViewModel>>(listado);
            return View(listadoMapeado);
                }

                return RedirectToAction("Index", "Login");


            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
                throw;
            }

        }





        [HttpPost("/EstadosCiviles/Create")]
        public IActionResult Create(string est_Descripcion)
        {
            try
            {
                if (HttpContext.Session.GetString("usu_Nombre") != null)
                {
                    ViewBag.usu_Nombre = HttpContext.Session.GetString("usu_Nombre");
                    ViewBag.suc_Descripcion = HttpContext.Session.GetString("suc_Descripcion");
                    ViewBag.usu_Id = HttpContext.Session.GetString("usu_ID");
                    ViewBag.suc_Id = HttpContext.Session.GetString("suc_Id");
                    int usucrea = int.Parse(HttpContext.Session.GetString("usu_ID"));
            tbEstadosCiviles esta = new tbEstadosCiviles();
            esta.est_Descripcion = est_Descripcion;
            esta.est_UsuarioCrea = usucrea;
            var est = _mapper.Map<tbEstadosCiviles>(esta);
            var result = _generalesService.CreateEstado(est);

            return RedirectToAction("Index");
                }

                return RedirectToAction("Index", "Login");


            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
                throw;
            }

        }


        public IActionResult Details(int id)
        {
            try
            {
                if (HttpContext.Session.GetString("usu_Nombre") != null)
                {
                    ViewBag.usu_Nombre = HttpContext.Session.GetString("usu_Nombre");
                    ViewBag.suc_Descripcion = HttpContext.Session.GetString("suc_Descripcion");
                    ViewBag.usu_Id = HttpContext.Session.GetString("usu_ID");
                    ViewBag.suc_Id = HttpContext.Session.GetString("suc_Id");

            var cates = _generalesService.DetallesEstados(id);
            EstadosCivilesViewModel model = new EstadosCivilesViewModel();

            if (cates != null && cates.Length > 0)
            {
                model.est_ID = cates[0];
                model.est_Descripcion = cates[1];
                model.est_UsuarioCrea = cates[2];
                model.est_UsuarioModi = cates[3];
                model.est_FechaCrea = Convert.ToDateTime(cates[4]);
                model.est_FechaModi = Convert.ToDateTime(cates[5]);

            }
            ViewBag.UsuCrea = model.est_UsuarioCrea;
            ViewBag.UsuModi = model.est_UsuarioModi;

            if (cates == null)
            {
                return RedirectToAction("Index"); // acá vamos a redireccionar a la pagina 404
            }
            return View(model);

                }

                return RedirectToAction("Index", "Login");


            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
                throw;
            }



        }


        [HttpGet("/EstadosCiviles/Editar/{id}")]
        public IActionResult Edit(int? id)
        {
            try
            {
                if (HttpContext.Session.GetString("usu_Nombre") != null)
                {
                    ViewBag.usu_Nombre = HttpContext.Session.GetString("usu_Nombre");
                    ViewBag.suc_Descripcion = HttpContext.Session.GetString("suc_Descripcion");
                    ViewBag.usu_Id = HttpContext.Session.GetString("usu_ID");
                    ViewBag.suc_Id = HttpContext.Session.GetString("suc_Id");


                    var listado = _generalesService.BuscarEstado(id);
                    return View(listado);

                }

                return RedirectToAction("Index", "Login");


            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
                throw;
            }

        }

        [HttpPost("/EstadosCiviles/Editar")]
        public IActionResult Edit(int est_ID, string est_Descripcion)
        {
            try
            {
                if (HttpContext.Session.GetString("usu_Nombre") != null)
                {
                    ViewBag.usu_Nombre = HttpContext.Session.GetString("usu_Nombre");
                    ViewBag.suc_Descripcion = HttpContext.Session.GetString("suc_Descripcion");
                    ViewBag.usu_Id = HttpContext.Session.GetString("usu_ID");
                    ViewBag.suc_Id = HttpContext.Session.GetString("suc_Id");
                    int usumodi = int.Parse(HttpContext.Session.GetString("usu_ID"));
            tbEstadosCiviles esta = new tbEstadosCiviles();
            esta.est_ID = est_ID;
            esta.est_Descripcion = est_Descripcion;
            esta.est_UsuarioModi = usumodi;

            var est = _mapper.Map<tbEstadosCiviles>(esta);
            var result = _generalesService.EditEstado(est);

            return RedirectToAction("Index");

                }

                return RedirectToAction("Index", "Login");


            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
                throw;
            }

        }

    }
}

Maquillaje/Maquillaje.WebUI/Views/EstadosCiviles/Details.cshtml
@model Maquillaje.WebUI.Models.EstadosCivilesViewModel

@{
    ViewData["Title"] = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-center">
    <img src="~/Content/iMG/giphy.gif" width="100" />
    <h1 style="color:black;font-family:'Segoe Print'">Detalles Estados Civiles</h1>
</div>
<div>
    <hr />



    <center>
        <dl class="dl-horizontal">

            <div class="row">
                <div class="col-sm-2"></div>

                <div class="col-sm-4">
            <dt>
                Estado Civil Id
            </dt>

            <dd class="form-control">
                @Html.DisplayFor(model => model.est_ID)
            </dd>
</div>


<div class="col-sm-4">
    <dt>
        Estado Civil Descripcion
    </dt>

    <dd class="form-control">
        @Html.DisplayFor(model => model.est_Descripcion)
    </dd>
</div>

    </dl>
    </center>
<br />
<div class="card">
    <div class="text-center">
        <div class="card-header" style="background-color: #ffd3d8">
            <h4 style="color:black;font-family:'Segoe Print'">Auditoria</h4>
        </div>


        <table class="table">
            <thead>
                <tr>
                    <th><strong>Acción</strong></th>
                    <th><strong>Usuario</strong></th>
                    <th><strong>Fecha</strong></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Creado</td>
                    <td>@ViewBag.UsuCrea</td>
                    <td>@Html.DisplayFor(model => model.est_FechaCrea)</td>
                </tr>
                <tr>
                    <td>Modificado</td>
                    <td>@ViewBag.UsuModi</td>
                    <td>@Html.DisplayFor(model => model.est_FechaModi)</td>
                </tr>

            </tbody>
        </table>

    </div>
    <div class="card-footer" style="background-color: #ffd3d8">
        <div class="text-center">
            <a class="btn btn-outline-secondary" asp-action="Index"><i class="icon-copy fa fa-reply" aria-hidden="true"></i> Volver</a>
        </div>
    </div>
</div>

Maquillaje/Maquillaje.WebUI/Views/EstadosCiviles/Index.cshtml
@model IEnumerable<Maquillaje.WebUI.Models.EstadosCivilesViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<div class="col-lg-12 mb-0 order-0">
    <div class="card" style="background-color: white">
        <div class="d-flex align-items-end row">
            <div class="col-sm-12">
                <div class="card-header" style="background-color:#ffd3d8">
                    <div class="text-center">
                        <img src="~/Content/iMG/giphy.gif" width="100" />
                        <h3 style="color:black;font-family:'Segoe Print'">Listado Estados Civiles</h3>
                    </div>
                </div>
                <div class="card-body">

                    <a class="btn btn-primary" data-toggle="modal" data-target="#CreateEst"><i class="icon-copy fa fa-plus" aria-hidden="true"></i> Nuevo</a>
                    <br />
                    <br />
                    <table class="table table-report -mt-2" id="DataTable">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.est_ID)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.est_Descripcion)
                                </th>

                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.est_ID)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.est_Descripcion)
                                    </td>


                                    <td>
                                        <a class="btn btn-primary" data-toggle="modal" data-target="#EditCate" onclick="Editar('@item.est_ID,@item.est_Descripcion')"><i class="icon-copy fa fa-pencil-square-o" aria-hidden="true"></i> Editar</a> |
                                        <a class="btn btn-outline-secondary" style="color: black" asp-action="Details" asp-route-id="@item.est_ID">
                                            <i class="icon-copy fa fa-file-text-o" aria-hidden="true"></i> Detalles
                                        </a> 
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>

@Html.Partial("_Create")
@Html.Partial("_Edit")

Maquillaje/Maquillaje.WebUI/Views/EstadosCiviles/_Create.cshtml
<Form action="@Url.Action("Create","EstadosCiviles")" method="post" id="createestado">

    <div class="modal fade" id="CreateEst" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="card-header" style="background-color:#ffd3d8">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

                    <div class="text-center">
                        <img src="~/Content/iMG/giphy.gif" width="100" />
                        <h3 style="color:black;font-family:'Segoe Print'">Cree una categoría</h3>
                    </div>
                </div>
                <div class="modal-body">
                    <br />
                    <br />
                    <label>Descripcion</label>
                    <input type="text" id="txtEstado" name="est_Descripcion" class="form-control" />
                    <br />
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" style="color: black" class="btn btn-primary"><i class="icon-copy fa fa-remove" aria-hidden="true"></i> Cancelar</button>
                    <button type="button" onclick="GuardarInsert()" class="btn btn-outline-secondary"> <i class="icon-copy fa fa-floppy-o" aria-hidden="true"></i> Guardar</button>
                </div>
            </div>
        </div>
    </div>
</Form>
<script>

    function GuardarInsert() {

        var siuu = true;


        if ($('#txtEstado').val() == "") {
            mostrarErrorToast("Campos requeridos.");
            siuu = false;
            console.log(1);

        }

        if (siuu) {
            $('#createestado').submit();
            mostrarSuccessToast("Se ha ingresado correctamente los datos.")
        }

    };

</script>

Maquillaje/Maquillaje.WebUI/Views/EstadosCiviles/_Edit.cshtml
<Form action="@Url.Action("Edit","EstadosCiviles")" id="EditEst" method="post">

    <div class="modal fade" id="EditEsta" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="card-header" style="background-color:#ffd3d8">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

                    <div class="text-center">
                        <img src="~/Content/iMG/giphy.gif" width="100" />
                        <h3 style="color:black;font-family:'Segoe Print'">Edite un Estado Civil</h3>
                    </div>
                </div>

                <div class="modal-body">
                    <br />
                    <input type="text" hidden id="txtEstId" name="est_ID" class="form-control" />
                    <label>Descripcion</label>
                    <input type="text" id="txtEstDescripcion" name="est_Descripcion" class="form-control" />
                    <br />
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" style="color: black" class="btn btn-primary"><i class="icon-copy fa fa-remove" aria-hidden="true"></i> Cancelar</button>
                    <button type="button" onclick="GuardarDatos()" class="btn btn-outline-secondary"> <i class="icon-copy fa fa-floppy-o" aria-hidden="true"></i> Guardar</button>
                </div>
            </div>
            </div>
        </div>

</Form>
<script>

    function Editar(cadena) {
        var datastring = cadena;
        var data = datastring.split(',');
        $("#txtEstId").val(data[0]);
        $("#txtEstDescripcion").val(data[1]);
        $("#EditEsta").modal('show');
    };


    function GuardarDatos() {

        if ($("#txtEstDescripcion").val() == "") {
            mostrarErrorToast("Campos requeridos.");
            stop();
        }
        else {
            $('#EditEst').submit();
            mostrarSuccessToast("Se ha ingresado correctamente los datos.")

        }
    };

</script>