Maquillaje/Maquillaje.WebUI/Controllers/SucursalController.cs
using AutoMapper;
using Maquillaje.BusinessLogic.Services;
using Maquillaje.DataAccess;
using Maquillaje.Entities.Entities;
using Maquillaje.WebUI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Maquillaje.WebUI.Controllers
{
    public class SucursalController : Controller
    {

        private readonly GeneralesService _generalesService;
        private readonly IMapper _mapper;
        public TiendaContext db = new TiendaContext();

        public SucursalController(GeneralesService generalesService, IMapper mapper)
        {
            _generalesService = generalesService;
            _mapper = mapper;
        }

        [HttpGet("/Sucursal/Listado")]
        public IActionResult Index()
        {
            try
            {
                if (HttpContext.Session.GetString("usu_Nombre") != null)
                {
                    ViewBag.usu_Nombre = HttpContext.Session.GetString("usu_Nombre");
                    ViewBag.suc_Descripcion = HttpContext.Session.GetString("suc_Descripcion");
                    ViewBag.usu_Id = HttpContext.Session.GetString("usu_ID");
                    ViewBag.suc_Id = HttpContext.Session.GetString("suc_Id");

            ViewBag.deptoCrea = new SelectList(db.Vw_Gral_tbDepartamentos_DDL, "depto", "dep_Descripcion");
            var listado = _generalesService.ListadoSucursales();
            var ListadoMapeado = _mapper.Map<IEnumerable<SucursalesViewModel>>(listado);
            return View(ListadoMapeado);
                }

                return RedirectToAction("Index", "Login");


            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
                throw;
            }

        }


        [HttpGet("/Sucursal/Create")]

        public IActionResult Create()
        {
            try
            {
                if (HttpContext.Session.GetString("usu_Nombre") != null)
                {
                    ViewBag.usu_Nombre = HttpContext.Session.GetString("usu_Nombre");
                    ViewBag.suc_Descripcion = HttpContext.Session.GetString("suc_Descripcion");
                    ViewBag.usu_Id = HttpContext.Session.GetString("usu_ID");
                    ViewBag.suc_Id = HttpContext.Session.GetString("suc_Id");

            ViewBag.deptoCrea = new SelectList(db.Vw_Gral_tbDepartamentos_DDL, "depto", "dep_Descripcion");
            return View();
                }

                return RedirectToAction("Index", "Login");


            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
                throw;
            }

        }



        //[HttpGet("/Sucursal/CargarMunicipios/{depto}")]
        //public JsonResult CargarMunicipios(int depto)
        //{

        //    var ddl = db.UDF_Gral_tbMunicipio_DDL(depto).ToList();

        //    return Json(ddl);

        //}




        public IActionResult Details(int id)
        {
            try
            {
                if (HttpContext.Session.GetString("usu_Nombre") != null)
                {
                    ViewBag.usu_Nombre = HttpContext.Session.GetString("usu_Nombre");
                    ViewBag.suc_Descripcion = HttpContext.Session.GetString("suc_Descripcion");
                    ViewBag.usu_Id = HttpContext.Session.GetString("usu_ID");
                    ViewBag.suc_Id = HttpContext.Session.GetString("suc_Id");

            var cates = _generalesService.DetallesSucu(id);
            SucursalesViewModel model = new SucursalesViewModel();

            if (cates != null && cates.Length > 0)
            {
                model.suc_Id = cates[0];
                model.suc_Municipio = cates[1];
                model.suc_Descripcion = cates[2];
                model.suc_UsuCrea = cates[3];
                model.suc_UsuModi = cates[4];
                model.suc_FechaCrea = Convert.ToDateTime(cates[5]);
                model.suc_FechaModi = Convert.ToDateTime(cates[6]);

            }
            ViewBag.UsuCrea = model.suc_UsuCrea;
            ViewBag.UsuModi = model.suc_UsuModi;

            if (cates == null)
            {
                return RedirectToAction("Index"); // acá vamos a redireccionar a la pagina 404
            }
            return View(model);
                }

                return RedirectToAction("Index", "Login");


            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
                throw;
            }




        }



        [HttpPost("/Sucursal/Create")]
        public IActionResult Create(string suc_Descripcion, int suc_MunicipioCrea)
        {
            try
            {
                if (HttpContext.Session.GetString("usu_Nombre") != null)
                {
                    ViewBag.usu_Nombre = HttpContext.Session.GetString("usu_Nombre");
                    ViewBag.suc_Descripcion = HttpContext.Session.GetString("suc_Descripcion");
                    ViewBag.usu_Id = HttpContext.Session.GetString("usu_ID");
                    ViewBag.suc_Id = HttpContext.Session.GetString("suc_Id");
                    int usucrea = int.Parse(HttpContext.Session.GetString("usu_ID"));
            tbSucursales sucu = new tbSucursales();
            sucu.suc_Descripcion = suc_Descripcion;
            sucu.suc_Municipio = suc_MunicipioCrea;
            sucu.suc_UsuCrea = usucrea;
            var suc = _mapper.Map<tbSucursales>(sucu);
            var result = _generalesService.CreateSucursales(suc);

            return RedirectToAction("Index");
                }

                return RedirectToAction("Index", "Login");


            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
                throw;
            }


        }

        #region Cargar Info

        //[HttpGet("/Sucursal/CargarMunicipios/{depto}")]
        //public JsonResult CargarMunicipios(int depto)
        //{

        //    var ddl = db.UDF_Gral_tbMunicipio_DDL(depto).ToList();
        //    return Json(ddl);

        //}

        //[HttpGet("/Sucursal/CargarInfo/{sucu_ID}")]
        //public JsonResult CargarInfo(int sucu_ID)
        //{

        //    var ddl = db.UDF_Gral_tbSucursalesInfo_DDL(sucu_ID).ToList();

        //    return Json(ddl);

        //}
        #endregion


        [HttpPost("/Sucursales/Cargar")]
        public JsonResult Cargar(int sucu_ID)
        {

            var tbSucursales = _generalesService.LlenarSucursal(sucu_ID);

            return Json(tbSucursales);
        }



        [HttpGet("/Sucursales/CargarDepartamento")]
        public JsonResult CargarDDLdepto()
        {

            var tbSucursales = _generalesService.CargaDep();

            return Json(tbSucursales);
        }



        [HttpPost("/Sucursales/CargarMunicipio/{dep_ID}")]
        public JsonResult CargarDdlmuni(int dep_ID)
        {

            var tbSucursales = _generalesService.CargaMuni(dep_ID);

            return Json(tbSucursales);
        }



        [HttpPost("/Sucursales/Editar")]
        public ActionResult EditarSucursales(tbSucursales tbSucursales)
        {
            _generalesService.EditarSucursal(tbSucursales);
            
            return RedirectToAction("Index");
        }




        [HttpPost("/Sucursal/Eliminar/")]
        public IActionResult Delete(int suc_Id)
        {
            try
            {
                if (HttpContext.Session.GetString("usu_Nombre") != null)
                {
                    ViewBag.usu_Nombre = HttpContext.Session.GetString("usu_Nombre");
                    ViewBag.suc_Descripcion = HttpContext.Session.GetString("suc_Descripcion");
                    ViewBag.usu_Id = HttpContext.Session.GetString("usu_ID");
                    ViewBag.suc_Id = HttpContext.Session.GetString("suc_Id");
                    int usumodi = int.Parse(HttpContext.Session.GetString("usu_ID"));
            tbSucursales suc = new tbSucursales();
            suc.suc_Id = suc_Id;
                    suc.suc_usuModi = usumodi;


            var sucu = _mapper.Map<tbSucursales>(suc);
            var result = _generalesService.DeleteSucursales(sucu);


            return RedirectToAction("Index");

                }

                return RedirectToAction("Index", "Login");


            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
                throw;
            }

        }


    }
}

Maquillaje/Maquillaje.WebUI/Views/Sucursal/Details.cshtml
@model Maquillaje.WebUI.Models.SucursalesViewModel

@{
    ViewData["Title"] = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-center">
    <img src="~/Content/iMG/giphy.gif" width="100" />
    <h1 style="color:black;font-family:'Segoe Print'">Detalles Sucursales</h1>
</div>
<div>
    <hr />



    <center>
        <dl class="dl-horizontal">

            <div class="row">
                <div class="col-sm-2"></div>

                <div class="col-sm-4">
            <dt>
                Sucursal 
            </dt>

            <dd class="form-control">
                @Html.DisplayFor(model => model.suc_Descripcion)
            </dd>
</div>


<div class="col-sm-4">
    <dt>
        Ciudad de ubicación
    </dt>

    <dd class="form-control">
        @Html.DisplayFor(model => model.suc_Municipio)
    </dd>
</div>

    </dl>
    </center>
<br />
<div class="card">
    <div class="text-center">
        <div class="card-header" style="background-color: #ffd3d8">
            <h4 style="color:black;font-family:'Segoe Print'">Auditoria</h4>
        </div>


        <table class="table">
            <thead>
                <tr>
                    <th><strong>Acción</strong></th>
                    <th><strong>Usuario</strong></th>
                    <th><strong>Fecha</strong></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Creado</td>
                    <td>@ViewBag.UsuCrea</td>
                    <td>@Html.DisplayFor(model => model.suc_FechaCrea)</td>
                </tr>
                <tr>
                    <td>Modificado</td>
                    <td>@ViewBag.UsuModi</td>
                    <td>@Html.DisplayFor(model => model.suc_FechaModi)</td>
                </tr>

            </tbody>
        </table>

    </div>
    <div class="card-footer" style="background-color: #ffd3d8">
        <div class="text-center">
            <a class="btn btn-outline-secondary" asp-action="Index"><i class="icon-copy fa fa-reply" aria-hidden="true"></i> Volver</a>
        </div>
    </div>
</div>

Maquillaje/Maquillaje.WebUI/Views/Sucursal/Index.cshtml
@model IEnumerable<Maquillaje.WebUI.Models.SucursalesViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<div class="col-lg-12 mb-0 order-0">
    <div class="card" style="background-color: white">
        <div class="d-flex align-items-end row">
            <div class="col-sm-12">
                <div class="card-header" style="background-color:#ffd3d8">
                    <div class="text-center">
                        <img src="~/Content/iMG/giphy.gif" width="100" />
                        <h3 style="color:black;font-family:'Segoe Print'">Listado Sucursales</h3>
                    </div>
                </div>
                <div class="card-body">

                    <a class="btn btn-primary" data-toggle="modal" data-target="#CreateSuc"><i class="icon-copy fa fa-plus" aria-hidden="true"></i> Nuevo</a>
                    <br />
                    <br />
                    <table class="table table-report -mt-2" id="DataTable">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.suc_Id)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.suc_Descripcion)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.suc_Municipio)
                                </th>

                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.suc_Id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.suc_Descripcion)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.suc_Municipio)
                                    </td>
                                    <td>
                                        <a class="btn btn-primary" data-toggle="modal" data-target="#editar-modal" onclick="Editar(@item.suc_Id)"><i class="icon-copy fa fa-pencil-square-o" aria-hidden="true"></i> Editar</a> |
                                        <a class="btn btn-outline-secondary" style="color: black" asp-action="Details" asp-route-id="@item.suc_Id">
                                            <i class="icon-copy fa fa-file-text-o" aria-hidden="true"></i> Detalles
                                        </a> |
                                        <a class="btn btn-outline-success" onclick="ShowModal(@item.suc_Id)" data-id="@item.suc_Id">
                                            <i class="icon-copy fa fa-trash" aria-hidden="true"></i> Eliminar
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>
@Html.Partial("_Create");
@Html.Partial("_Edit");
@Html.Partial("_Delete");

Maquillaje/Maquillaje.WebUI/Views/Sucursal/_Create.cshtml
<Form action="@Url.Action("Create","Sucursal")" id="createsuc" method="post">

    <div class="modal fade" id="CreateSuc" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="card-header" style="background-color:#ffd3d8">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

                    <div class="text-center">
                        <img src="~/Content/iMG/giphy.gif" width="100" />
                        <h3 style="color:black;font-family:'Segoe Print'">Cree una Sucursal</h3>
                    </div>
                </div>
                <div class="modal-body">
                    <br />
                    <div class="row">
                        <div class="col-sm-6">
                            <label>Departamento</label>
                            <select id="deptoCrea" class="form-control" name="deptoCrea" asp-items="ViewBag.deptoCrea"></select>
                        </div>

                        <div class="col-sm-6">
                            <label>Ciudad</label>
                            <select id="suc_MunicipioCrea" class="form-control" name="suc_MunicipioCrea"></select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <label>Descripcion</label>
                            <input type="text" class="form-control" id="suc_DescripcionCrea" name="suc_Descripcion" />
                        </div>
                    </div>
                    <br />
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" style="color: black" class="btn btn-primary"><i class="icon-copy fa fa-remove" aria-hidden="true"></i> Cancelar</button>
                    <button type="button" onclick="GuardarInsert()" class="btn btn-outline-secondary"> <i class="icon-copy fa fa-floppy-o" aria-hidden="true"></i> Guardar</button>
                </div>
            </div>
        </div>
    </div>
</Form>


<script>


    $("#deptoCrea").change(function () {

        var depto = $("#deptoCrea").val();

        console.log(depto);

        $.ajax({
            url: "/Sucursal/CargarMunicipios/" + depto,
            method: "GET",
            dataType: "json",
            contentType: "application/json; charset=utf-8",

            success: function (data) {
                $("#suc_MunicipioCrea").empty();
                $("#suc_MunicipioCrea").append("<option value= '0' >Seleccione un Municipio</option>");

                $.each(data, function (i, value) {
                    $("#suc_MunicipioCrea").append("<option value='" + value.mun_ID + "'>" + value.mun_Descripcion + "</option>");
                })
            }
        })
    });


    function GuardarInsert() {

        var siuu = true;


        if ($('#suc_DescripcionCrea').val() == "" || $('#deptoCrea').val() == 0 || $('#suc_MunicipioCrea').val() == 0) {
            mostrarErrorToast("Campos requeridos.");
            siuu = false;
            console.log(1);
        }


        if (siuu) {
            $('#createsuc').submit();
            mostrarSuccessToast("Se ha ingresado correctamente los datos.")
        }

    };


</script>

Maquillaje/Maquillaje.WebUI/Views/Sucursal/_Delete.cshtml
<form action="@Url.Action("Delete","Sucursal")" method="post" id="deleteform">

    <div class="modal fade" id="DeleteSuc" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm modal-dialog-centered">
            <div class="modal-content bg-danger text-white">
                <div class="modal-body text-center">
                    <h3 class="text-white mb-15"><i class="fa fa-exclamation-triangle"></i> Alert</h3>
                    <input type="hidden" id="suc_Id" name="suc_Id" />
                    <div class="text-gray-600 mt-2">
                        ¿Está seguro de eliminar el registro?
                        <br />
                        <br />
                        <button type="button" id="confirmar" class="btn btn-light">OK</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>

    function ShowModal(suc_Id) {
        $('#DeleteSuc').modal('show');
        $("#confirmar").click(function () {
            var id = suc_Id;

            $.ajax({
                url: "/Sucursal/Eliminar",
                type: "POST",
                data: { suc_Id: id },
                success: function () {
                    window.location.href = "/Sucursal/Listado";
                },
                error: function () {
                    alert("Error al eliminar el registro.");
                }
            });
        });
    };
</script>

Maquillaje/Maquillaje.WebUI/Views/Sucursal/_Edit.cshtml
            <form method="post">
                <div class="modal fade" id="editar-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="card-header" style="background-color:#ffd3d8">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

                                <div class="text-center">
                                    <img src="~/Content/iMG/giphy.gif" width="100" />
                                    <h3 style="color:black;font-family:'Segoe Print'">Editar Sucursal</h3>
                                </div>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <label>Municipio</label>
                                        <select id="ddlMuni2" name="ddlMuni2" class="form-control"></select>
                                        <label style="color:red" id="emuni2" name="emuni2" hidden>Debe llenar este campo</label>
                                        
                                    </div>
                                    <div class="col-sm-6">
                                        <label>Departamento</label>
                                        <select id="ddlDepto2" name="ddlDepto2" class="form-control"></select>
                                        <label style="color:red" id="edep2" name="edep2" hidden>Debe llenar este campo</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">

                                        <label>Sucursal</label>
                                        <input type="text" id="txtSucursal2" name="txtSucursal2" class="form-control" />
                                        <label style="color:red" id="esucu2" name="esucu2" hidden>Debe llenar este campo</label>

                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-light" data-dismiss="modal">Cerrar</button>
                                <button type="button" id="btnEditar" name="btnEditar" class="btn btn-primary">Guardar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            @*<script src="~/js/Sucursales/EditarSucursales.js"></script>*@
            <script>



                function Editar(sucu_ID) {
                    $("#editar-modal").modal('show');
                    var sucu_ID = sucu_ID;
                    var sucursalID = sucu_ID;
                    console.log(sucu_ID);
                    $.ajax({
                        url: "/Sucursales/Cargar",
                        method: "POST",
                        data: { sucu_ID: sucu_ID },
                        success: function (data) {
                            $.each(data, function (i, value) {
                                $("#txtSucursal2").val(value.suc_Descripcion);
                                $("#ddlDepto2").val(value.dep_ID);
                                console.log(value.dep_ID);
                                console.log(value.mun_ID);
                                var ciudad = value.mun_ID;



                                var dep_ID = $("#ddlDepto2").val();
                                console.log(value.dep_ID);

                                $.ajax({
                                    url: "/Sucursales/CargarMunicipio/" + dep_ID,
                                    method: "POST",
                                    dataType: "json",
                                    contentType: "application/json; charset=utf-8",
                                    data: { dep_ID: dep_ID },


                                    success: function (data) {
                                        $("#ddlMuni2").empty();
                                        $.each(data, function (i, value) {
                                            $("#ddlMuni2").append("<option value='" + value.mun_ID + "'>" + value.mun_Descripcion + "</option>")
                                        })
                                        $("#ddlMuni2").val(ciudad);
                                    }
                                })

                            })
                        }
                    })
                    $("#ddlDepto2").change(function () {
                        var dep_ID = $("#ddlDepto2").val();
                        $.ajax({
                            url: "/Sucursales/CargarMunicipio/" + dep_ID,
                            method: "POST",
                            dataType: "json",
                            contentType: "application/json; charset=utf-8",
                            data: { dep_ID: dep_ID },
                            success: function (data) {
                                $("#ddlMuni2").empty();
                                $.each(data, function (i, value) {
                                    $("#ddlMuni2").append("<option value='" + value.mun_ID + "'>" + value.mun_Descripcion + "</option>")
                                })
                            }
                        })
                    })
                    $("#btnEditar").click(function () {
                        var sucursal = $("#txtSucursal2").val();
                        console.log(sucursal);
                        var muni = $("#ddlMuni2").val();
                        console.log(muni);

                        if (sucursal == "") {
                            $("#esucu2").show();
                        }
                        else {
                            $("#esucu2").hide();
                            $.ajax({
                                url: "/Sucursales/Editar",
                                method: "POST",
                                data: { suc_Descripcion: sucursal, mun_ID: muni, suc_ID: sucu_ID },
                                success: function (data) {
                                    window.location.reload();
                                }
                            })
                        }
                    })
                }

            </script>